# Generated by Django 3.1.5 on 2021-01-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210123_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='i am a coder'),
            preserve_default=False,
        ),
    ]
